InstituteInfo/urls.py
from django.conf.urls.defaults import patterns , url
from InstituteInfo.views import  StudentVerification,EditImage\
    , ajax_save_images, CsvInfoUpload, registrationFromCsv,\
    delete_student,groups,change_wall_group, delete_faculty,delete_csv,showCsvData,registerStudent,BulletinInfo,messages

urlpatterns = patterns( '',

     # url( r'^(?P<insti_id>[-\d]+)/$', InstituteProfile.as_view(), name = 'institute_profile' ),


	 url(r'^student_verification/$', StudentVerification.as_view(), name = 'student_verification' ),
	 # url( r'^delete/(?P<id>[-\d]+)$', delete_post, name = 'delete_post' ),

	 url( r'^edit_image/$', EditImage.as_view(), name = 'edit_image' ),

	 url( r'^ajax-save-image/$', ajax_save_images, name = 'ajax_save_image' ),

	 url( r'^csv/$', CsvInfoUpload.as_view(), name = 'csv_upload' ),

	 url( r'^register_users/$', registrationFromCsv, name = 'register_users' ),

	 # url( r'^connected_students/$', students_connected_to_institute , name = 'connected_students' ),

	 url( r'^delete_student/$', delete_student , name = 'delete_student' ),

     url( r'^delete_faculty/$', delete_faculty , name = 'delete_faculty' ),

	 url( r'^groups/(?P<group_id>[-\d]+)/(?P<student_id>[-\d]+)$', groups , name = 'groups' ),

	 url( r'^wallgroup/(?P<group_id>[-\d]+)/(?P<wall_id>[-\d]+)$', change_wall_group , name = 'change_wall_group' ),

     url( r'^delete_csv$', delete_csv , name = 'delete_csv' ),

     url( r'^csv_data/(?P<csv_id>[-\d]+)/$', showCsvData , name = 'show_csv_data' ),

     url( r'^register_student/$', registerStudent , name = 'register_student' ),

     url(r'^bulletin/(?P<bulletin_id>[-\d]+)/$',BulletinInfo.as_view(), name='show_bulletin'),

     url(r'^messages/$',messages, name='messages')

)

casperF/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.defaults import patterns, include, url
from django.views.i18n import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.conf import settings
admin.autodiscover()

js_info_dict = {
    'packages': ('InstituteInfo',),
}

urlpatterns = patterns('',
    # Examples:
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^i18n/', include('django.conf.urls.i18n')),
    (r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict),
    (r'^jsi18n/(?P<packages>\S+?)/$', 'django.views.i18n.javascript_catalog'),
    # Uncomment the next line to enable the admin:
     url(r'^admin/', include(admin.site.urls)),
     url( r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT} ),
     url( r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT} ),
)
urlpatterns += staticfiles_urlpatterns()

urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.defaults import patterns, include, url
from django.views.i18n import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from userapp import urls
from django.conf import settings
from facultyinfo.views import FacultyDetail
admin.autodiscover()

js_info_dict = {
    'packages': ('InstituteInfo',),
}

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'myorganisation.views.home', name='home'),
    # url(r'^myorganisation/', include('myorganisation.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),


    #(r'%s' % settings.ASKBOT_URL, include('askbot.urls')),
    #(r'^cache/', include('keyedcache.urls')), - broken views disable for now
    #(r'^settings/', include('askbot.deps.livesettings.urls')),
    #(r'^followit/', include('followit.urls')),
    #(r'^robots.txt$', include('robots.urls')),
    (r'^i18n/', include('django.conf.urls.i18n')),

    (r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict),

    (r'^jsi18n/(?P<packages>\S+?)/$', 'django.views.i18n.javascript_catalog'),

    # Uncomment the next line to enable the admin:
     url(r'^admin/', include(admin.site.urls)),

     url( r'^', include( 'userapp.urls' ) ),

     url( r'^institute/', include( 'InstituteInfo.urls' ) ),
	
     url( r'^group_config/', include( 'group_config.urls' ) ),

     url( r'^student/', include( 'studentinfo.urls' ) ),

     url( r'^faculty/', include( 'facultyinfo.urls' ) ),

    # url( r'^(?P<user_id>[-\d]+)/(?P<username>[-\w]+)/$', FacultyDetail.as_view(), name = 'faculty_detail' ),

     #url( r'^online-exam/', include( 'questionnaire.urls' ) ),

     url( r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT} ),

     url( r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT} ),

     #(r'^photologue/', include('photologue.urls')),

     # (r'^messages/', include('persistent_messages.urls')),

     # (r'^comments/', include('django.contrib.comments.urls')),
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^rosetta/', include('rosetta.urls')),
    )
urlpatterns += staticfiles_urlpatterns()

InstituteInfo/models.py
from django.db import models
import datetime
from InstituteInfo.choices import USER_TYPE
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from master.models import MyUser


def file_path( instance,filename):
    return "uploads/csv/%s" %(filename )

def blog_file_path( instance, filename ):
    return "uploads/blog/%s" %(filename )


class Bulletin(models.Model):
    user = models.ForeignKey(MyUser)
    group = models.ForeignKey('group_config.UserGroup')#todo
    title = models.CharField(max_length=500)
    body = models.TextField()
    attachments = models.FileField(upload_to=blog_file_path,null=True,blank=True)
    date_posted = models.DateTimeField(default=datetime.datetime.now(), null= True)

    def __unicode__(self):
        return self.title

class Comment(models.Model):
    user = models.ForeignKey(MyUser)
    reply = models.CharField(max_length= 1000)
    bulletin = models.ForeignKey(Bulletin)
    posted = models.DateTimeField(auto_now_add=True,default=datetime.datetime.now())

    def __unicode__(self):
        return str(self.bulletin)

class CsvInfo(models.Model):
    # institute = models.ForeignKey( InstitueInfo )
    group = models.ForeignKey ( 'group_config.UserGroup' )
    type = models.CharField(max_length = 100,choices=USER_TYPE)
    file_upload = models.FileField( upload_to = file_path)
    objects = models.Manager()

    def __unicode__(self):
        return str(self.file_upload)

master/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from InstituteInfo.choices import INSTITUTE_TYPE,LIST_YEAR,USER_TYPE
from studentinfo.choices import STATUS_CHOICES
from django.db import models
from django.contrib.auth.models import ( AbstractUser)
# from group_config.models import UserGroup


def imagepath(instance, filename):
    """ Computes the infrastructure images upload path """
    return "uploads/user_images/%s/%s" % (instance.user.id, str(filename).replace(" ", "-"))


class MyUser(AbstractUser):
    photo = models.ImageField(upload_to=imagepath)
    user_type = models.CharField(max_length=25, choices=USER_TYPE)
    institute_type = models.CharField(max_length=25, choices=INSTITUTE_TYPE )
    establishment_year = models.IntegerField(blank=True, null=True, choices=LIST_YEAR )
    address = models.TextField()
    profile = models.BooleanField(default=False, blank=True)
    status = models.CharField(max_length=100, choices=STATUS_CHOICES, default='Pending')
    qualification = models.CharField(max_length=100)
    work_experience = models.CharField(max_length=100)
    rating = models.FloatField(default=0)
    unique_number = models.CharField(max_length=30)
    connections = models.ManyToManyField("self", through='UserSelf', symmetrical=False)

    def __unicode__(self):
        return self.username

def post_save_default_image(sender, instance, **kwargs):
    if kwargs['created'] is True:
        photo = "uploads/user_images/%s/%s" % ('default', str('images.jpeg').replace(" ", "-"))
        instance.photo = photo
        instance.save()

class UserSelf(models.Model):
    source = models.ForeignKey(MyUser, related_name='source')
    target = models.ForeignKey(MyUser, related_name='target')
    group = models.ForeignKey('group_config.UserGroup', null=True, blank=True)

post_save.connect(post_save_default_image, sender= MyUser)

InstituteInfo/forms.py
__author__ = 'harshit'


from django import forms
from InstituteInfo.models import  Bulletin
from models import CsvInfo


class BulletinForm(forms.ModelForm):
    class Meta:
        model = Bulletin
        fields = ('title','body','attachments','group')


class CsvInfoForm(forms.ModelForm):
     class Meta:
         model = CsvInfo
         exclude = ('institute',)

     def clean_file_upload(self):
         file_obj = self.cleaned_data['file_upload']
         if file_obj.size > 51200:
             raise forms.ValidationError("You can upload a file of size 50 KB")
         return file_obj

templates/instituteinfo/crop_image.html
{% extends "layouts/layout_base_2_columns.html" %}
{% block A_1 %}

{% block css %}
<link rel="stylesheet" href="{{ STATIC_URL }}default/media/bootstrap/css/bootstrap.css" type="text/css" media="all" />
<link type="text/css" rel="stylesheet" media="all" href="{{ STATIC_URL }}default/media/style/headerTwitter.css" />
<link type="text/css" rel="stylesheet" media="all" href="{{ STATIC_URL }}default/media/style/homepage.css" />
<link rel="stylesheet" href="{{ STATIC_URL }}default/media/style/jquery.Jcrop.css" type="text/css" media="all" />
<link rel="stylesheet" href="{{ STATIC_URL }}default/media/style/thickbox.css" type="text/css" media="all" />
<link rel="stylesheet" href="{{ STATIC_URL }}default/media/style/div_new.css" type="text/css" media="all" />
{% endblock css %}


{% block js %}
<script src="{{ STATIC_URL }}default/media/js/jquery-1.7.2.min.js"></script>
<script src="{{ STATIC_URL }}default/media/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}default/media/js/jquery-1.7.2.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}default/media/js/thickbox.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}default/media/js/jquery.Jcrop.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}default/media/js/crop_image.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}default/media/js/utils_new.js"></script>
{% endblock js %}




<form enctype="multipart/form-data" method="post" class="form-horizontal"> {% csrf_token %}
{% for each_field in form.visible_fields %}
<div class="control-group">
<label class="control-label" for="id_{{ each_field.label|lower }}">{{ each_field.label }}</label>
<div class="controls">
{%  if each_field.errors %}
{{ each_field.errors }}
{% endif %}
{{each_field}}
</div>
</div>
{% endfor %}

<div id="div_cointainer_photo" style="display:none"></div>
<div style="text-align:center;padding:20px;">
<a href="#TB_inline?height=400&amp;width=700&amp;inlineId=div_cointainer_photo" class="thickbox" id='a_tag'></a>
</div>
<input type="hidden" value="{}" name="crop_dictionary" id="id_cropdict">

<input class="btn btn-primary" type="submit" value ="Add Image"></button>
</form>

{% endblock A_1 %}

templates/instituteinfo/institute_profile.html
{% extends "layouts/layout_base_2_columns.html" %}

{% block A_1 %}

    <form style='height: 0px;width:0px; overflow:hidden;' enctype="m    ultipart/form-data" method="post" class="form-horizontal"> {% csrf_token %}
    <label class="control-label" for="id_photo"></label>
        <input id="upfile"  type="file" name="photo">
    <input type="hidden" value="{}" name="crop_dictionary" id="id_cropdict">
    </form>

    <div style =" border-style: solid;border-width: 1px;left: 123px;position: absolute;right: 123px;top: 0">
    <img  src ="{{ MEDIA_URL }}uploads/student_signature/5/personal2.jpg">
    </div>

    <div class ="logo">
        <img  src ="{{ MEDIA_URL }}{{ image_path.0.photo }}" style="height:100%;width:100%">
        <div id = 'editImage' style="margin-top: -20px;display: none;" >
          <strong><div style= "cursor:pointer;" onclick="getFile()">Edit Image</div></strong>
        </div>
    </div>

{#{% include "persistent_messages/message/includes/messages.jquery.html" %}#}





















    <form class="formStudents">
        <div class="modal-header">
            <a href ={% url 'connected_students' %}><strong>Students</strong></a>
        </div>
        <div class="modal-body">
             {% for student_image in  student_images %}
                <div class="studentImage">
                    <img  src ="{{ MEDIA_URL }}{{ student_image.images__photo }}" height="100%" width="100%">
                <div id = 'editImage' style="margin-top: -20px">
                    <a href={%url 'profile' student_image.user_id  student_image.user__username%}>{{ student_image.user__username }}</a>
                </div>
                </div>
            {% endfor %}
        </div>
    </form>

      <form class="formFaculty">
        <div class="modal-header">
            <a href ={% url 'connected_faculty' %}><strong>Faculty</strong></a>
        </div>
        <div class="modal-body">
            {% for faculty_image in  faculty_images %}
                <div class="studentImage">
                    <img  src ="{{ MEDIA_URL }}{{ faculty_image.image__photo }}" style="height:100%;width:100%">
                    <div id = 'editImage' style="margin-top: -20px">
                        <a href={%url 'profile' faculty_image.user_id  faculty_image.user__username%}>{{ faculty_image.user__username }}</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </form>



    {% for each_student in student_users %}
    <form class="logo form-frienRequest" style="margin-top: 300px " method="post" action="{% url 'student_verification' %}"> {% csrf_token %}
        {{ each_student.username}}
        <input type = "hidden" value = "{{ each_student.id }}" name = "student_id"><br>
        <input class="btn btn-primary" id="id_submit" name = 'status' type="submit"  value="Confirm" />
        <input class="btn btn-primary" id="id_submit" name = 'status' type="submit"  value="Reject" />
    </form>
    {% endfor %}

    <form class="form-wallPost" method="post" style= "width: 541px ">{% csrf_token %}
        <div class="modal-header">
            {{ request.user.id }}
            <h2>Bulletin Board:Post Your Bulletins Here.</h2>
        </div>
        <div class="modal-body">
        {% for each_field in bulletinForm.visible_fields %}
            {%  if each_field.errors %}
                {{ each_field.errors }}
            {% endif %}
            {{ each_field }}

        {% endfor %}
        </div>
        <div class="modal-footer">
            <input class="btn btn-primary" type="submit" style="float: right" value ="Post My Bulletin"></button>
        </div>
    </form>
    <div class="clear"></div>




{#endless#}
{% include page_template %}
{#end of endless :D #}



<script type="text/javascript">
    function changeGroup(group_id,wall_id)
    {
        $.get('/institute/wallgroup/'+group_id+'/'+wall_id);
    }

    $("document").ready(function(){
        $(".icon-trash").hide()
        $(".wallGroups").hide()
    });
        $(".wallPost").hover(function(){
            $(this).find(".icon-trash").show()
            $(this).find(".wallGroups").show()
            $(".wallPost").mouseleave(function(){
                $(".icon-trash").hide()
                $(".wallGroups").hide()
            })
           });

    $(".logo").hover(function(){
            $(this).find("#editImage").show()
            $(".logo").mouseleave(function(){
                $(this).find("#editImage").hide()
            })

           });

function getFile(){
        document.getElementById("upfile").click();
    }

</script>

{% block js %}
    {{ block.super }}
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="{{ STATIC_URL }}endless_pagination/js/endless-pagination.js"></script>
{#    <script src="{{ STATIC_URL }}endless_pagination/js/endless.js"></script>#}
{#    <script src="{{ STATIC_URL }}endless_pagination/js/endless_on_scroll.js"><  /script>#}
    <script>
        $.endlessPaginate({
            paginateOnScroll: true,
            paginateOnScrollMargin: 1
        });
    </script>
{% endblock %}

{% endblock A_1 %}

templates/instituteinfo/myfaculty.html
{% extends "layouts/layout_base_2_columns.html" %}

{% block A_1 %}
    <div style =" border-style: solid;border-width: 1px;left: 123px;position: absolute;right: 123px;top: 0">
    <img  src ="{{ MEDIA_URL }}uploads/student_signature/5/personal2.jpg">
    </div>


            <div style="margin: 255px 188px 0px 220px">
            {% for faculty in faculties %}
                    <div class="listingFaculty">
                        <div class="studentImage">
                            <img  src ="{{ MEDIA_URL }}{{ faculty.image__photo }}" style="height:100%;width:100%">
                         </div>
                        <div class="facultyName">
                            <a href={% url profile faculty.user_id faculty.user__username %}>
                         {{ faculty.user__first_name }}{{ faculty.user__last_name }}</a>
                        </div>

                        {% if group_type == 'Institute' %}
                            <form enctype="multipart/form-data" method="post" action="{% url delete_faculty %}"> {% csrf_token %}
                            <input type="hidden" value = "{{ each.id }}" name="id">
                             <div class="clear"></div>
                            <div class="listingButton">
                                <input class="btn btn-primary" type="submit" value ="Delete"></button>
                            </div
                            </form>
                        {% endif %}

                    </div>

            {% endfor %}
            </div>

{% endblock A_1 %}

templates/instituteinfo/mystudents.html
{% extends "layouts/layout_base_2_columns.html" %}

{% block A_1 %}



        <div style =" border-style: solid;border-width: 1px;left: 123px;position: absolute;right: 123px;top: 0">
            <img  src ="{{ MEDIA_URL }}uploads/student_signature/5/personal2.jpg">
        </div>


          <div style="margin: 255px 188px 0px 220px">
            {% for student in connected_students %}
                    <div class="listingFaculty">


                        <div class="studentImage">
                            <img  src ="{{ MEDIA_URL }}{{ student.images__photo }}" height="100%" width="100%">
                         </div>
                        <div class="facultyName">
                            <a href={% url profile student.user_id student.user__username %}>
                         {{ student.user__first_name }}
                         {{ student.user__username }}</a>
                        </div>

                        {% if group_type == 'Institute' %}
                            <form enctype="multipart/form-data" method="post" action="{% url delete_faculty %}"> {% csrf_token %}
                                <input type="hidden" value = "{{ each.id }}" name="id">
                                 <div class="clear"></div>
                                <div class="listingButton">
                                    <input class="btn btn-primary" type="submit" value ="Delete"></button>
                                </div
                            </form>
                        {% endif %}
                    </div>

            {% endfor %}
            </div>
        </div>

{#                <form enctype="multipart/form-data" method="post" action="{% url delete_student %}"> {% csrf_token %}#}
{#                    <select class="group">#}
{#                        <option value="">None</option>#}
{#                        {% for group in groups %}#}
{#                            {% if group.id == each.insti_group__id %}#}
{#                                <option value="{{ group.id }}" selected="True">{{ group.name }}</option>#}
{#                            {% else %}#}
{#                                <option value="{{ group.id }}" class="groupName" onclick="changeGroup('{{ group.id }}','{{ each.id }}')">#}
{#                                    {{ group.name }}#}
{#                                </option>#}
{#                            {% endif %}#}
{#                        {% endfor %}#}
{#                    </select>#}
{#                </td>#}
{##}





<script type="text/javascript">
    function changeGroup(group_id,student_id)
    {

        $.get('/institute/groups/'+group_id+'/'+student_id);
    }
</script>
{#    $('.group').change(function(){#}
{#       alert('ok.tested');#}
{#    });#}

{##}
{#    #}
{#<script type="text/template" id="user-list-template" >#}
{#    <select id="group" name="group">#}
{#        <option value="">select a group</option>#}
{#        <% _.each(users,function(users){ %>#}
{#        <option value="<%= users.get('fields') %>"><%= users.get('fields') %></option>#}
{#        <% }); %>#}
{#    </select>#}
{#</script>#}
{##}
{##}
{#    <script>#}
{#        $.ajaxPrefilter( function( options, originalOptions, jqXHR ) {#}
{#        options.url = 'http://127.0.0.1:8000' + options.url;#}
{#        });#}
{##}
{#        var Users = Backbone.Collection.extend({#}
{#            url:'/institute/groups/'#}
{#        })#}
{##}
{#        var UserList = Backbone.View.extend({#}
{#            el:'.group',#}
{##}
{#            events:{#}
{#                "click .group":"doTest"#}
{#            },#}
{##}
{#            initialize: function() {#}
{#                this.clickHandler();#}
{#            },#}
{##}
{#            clickHandler: function() {#}
{##}
{#                var self = this;#}
{#                $('.group').click(function(e) {#}
{#                        self.doTest();#}
{#                });#}
{#            },#}
{##}
{#            doTest: function() {#}
{#                var that = this;#}
{#                var users = new Users;#}
{##}
{#                users.fetch()#}
{#                    success:function(users){#}
{#                        alert('test');#}
{#                        var template = _.template($('#user-list-template').html(),{users: users.models})#}
{#                        that.$el.html(template)#}
{#                    }#}
{#                })#}
{#            }#}
{#        })#}
{##}
{#        var Router = Backbone.Router.extend({#}
{#            routes:{#}
{#                '':'mygroups'#}
{#            }#}
{#        })#}
{##}
{#        var userList = new UserList();#}
{##}
{#        var router = new Router();#}
{#        router.on('route:mygroups',function(){#}
{#            userList.render();#}
{#        });#}
{##}
{#        Backbone.history.start();#}
{##}
{#    </script>#}
{% endblock A_1 %}

templates/instituteinfo/pagination.html
<div class="wallPostDiv">
{% load endless %}
{% paginate all_bulletins %}
{%  for bulletin in all_bulletins %}
    <div class="wallPost" >
        <div class="modal-header">
            {{bulletin.date_posted}} Posted By:{{ bulletin.user__username }}
            <select id ="wallGroup" select class="wallGroups">
                <option value="">None</option>
                {% for group in groups %}
                    {% if group.id == bulletin.group__id %}
                        <option value="{{ group.id }}" selected="True">{{ group.name }}</option>
                    {% else %}
                        <option value="{{ group.id }}" class="groupName" onclick="changeGroup('{{ group.id }}','{{ wall_post.id }}')">
                            {{ group.name }}
                        </option>
                    {% endif %}
                {% endfor %}
            </select>
            <a class="icon-trash"  style="float: right" href ="{% url 'delete_post' bulletin.id %}"></a>
        </div>
        <a href={% url 'show_bulletin' bulletin.id %}>{{ bulletin.title }}</a>
    </div>
{%  endfor  %}
{% show_more %}
</div>

templates/instituteinfo/search.html
{% extends "layouts/layout_base_2_columns.html" %}

{% block A_1 %}



{% if msg %}
   {{ msg }}
{% endif %}


{% if institutes_search_results %}
    {% for institute in institutes_search_results %}
        {{ institute.name }} {{ institute.description }}<br>
        <form class ="form-signin" method="post" action="{% url add_institutes %}"> {% csrf_token %}
            <input type="hidden" value="{{ institute.id }}" name="institute_id">
        <input class="btn btn-primary" type="submit" value ="Add to Myconnection"></button><br>
        </form>
    {% endfor %}

{% endif %}

{% if connected_institutes %}
{{ connected_institutes }}
{% endif %}




<form class = "form-connection" style="padding-bottom: 10px" enctype="multipart/form-data" class ="form-signin" method="post"> {% csrf_token %}

    {% for each_field in form.visible_fields %}

        {% if each_field.name == 'group' %}
            {{ each_field.label }}:<br>
            <select id="id_group" name="group" >
                {% for group in groups %}
                        <option value="{{ group.id }}" class="groupName">
                            {{ group.name }}
                        </option>
                {% endfor %}
            </select>
            <br>
        {% else %}
            {{ each_field.label }}:<br>
            {{ each_field }}
        {% endif %}
    {% endfor %}



    {% for each_field in form.visible_fields %}
            {%  if each_field.errors %}
            {{ each_field.errors }}
            {% endif %}
    {% endfor %}

    <input class="btn btn-primary" type="submit" value ="Upload"></button>
</form>
<div>
<table class="form-connection">
<tr>
    <th>
        Number
    </th>
    <th>
        Group
    </th>
    <th>
        Type
    </th>
    <th>
        Csv File Name
    </th>
    <th>
        Action
    </th>
</tr>

{% for csv_obj in csv_objs %}

        <tr>
            <form enctype="multipart/form-data" action = "{% url register_users %}"  method="post"> {% csrf_token %}
            <td>
                {{ forloop.counter }}
            </td>
            <td>
                {{ csv_obj.group__name }}
            </td>
            <td>{{ csv_obj.type }}</td>
            <td>
                <a href="{{ MEDIA_URL }}{{ csv_obj.file_upload }}">{{ csv_obj.file_upload }}</a>
            </td>

        <input type="hidden" value = "{{ csv_obj.id }}" name="csv_obj_id">
            <td>
                <input class="btn btn-primary" type="submit" value ="Register"></button>
            </td>
            </form>
            <td>
                <form enctype="multipart/form-data" action = "{% url delete_csv %}"  method="post"> {% csrf_token %}
                <input type="hidden" value = "{{ csv_obj.id }}" name="csv_obj_id">
                <input class="btn btn-primary" type="submit" value ="Delete"></button>
                </form>
            </td>
            <td>
                <a class="btn btn-primary" href="{% url show_csv_data csv_obj.id %}">Show Data</a>
            </td>
        </tr>

{% endfor %}
</table>
</div>

{% endblock A_1 %}

templates/instituteinfo/student_verification.html
{% for each_student in student_users %}
	<form  method="post" action="{% url student_verification %}"> {% csrf_token %}
	    {{ each_student.username}}
	    <input type = "hidden" value = "{{ each_student.id }}" name = "student_id">
	    <input id="id_submit" name = 'status' type="submit"  value="Confirm" />
	    <input id="id_submit" name = 'status' type="submit"  value="Reject" />
	</form>
{% endfor %}