casperF/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.defaults import patterns, include, url
from django.views.i18n import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.conf import settings
admin.autodiscover()

js_info_dict = {
    'packages': ('InstituteInfo',),
}

urlpatterns = patterns('',
    # Examples:
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^i18n/', include('django.conf.urls.i18n')),
    (r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict),
    (r'^jsi18n/(?P<packages>\S+?)/$', 'django.views.i18n.javascript_catalog'),
    # Uncomment the next line to enable the admin:
     url(r'^admin/', include(admin.site.urls)),
     url( r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT} ),
     url( r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT} ),
)
urlpatterns += staticfiles_urlpatterns()

urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.defaults import patterns, include, url
from django.views.i18n import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from userapp import urls
from django.conf import settings
from facultyinfo.views import FacultyDetail
admin.autodiscover()

js_info_dict = {
    'packages': ('InstituteInfo',),
}

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'myorganisation.views.home', name='home'),
    # url(r'^myorganisation/', include('myorganisation.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),


    #(r'%s' % settings.ASKBOT_URL, include('askbot.urls')),
    #(r'^cache/', include('keyedcache.urls')), - broken views disable for now
    #(r'^settings/', include('askbot.deps.livesettings.urls')),
    #(r'^followit/', include('followit.urls')),
    #(r'^robots.txt$', include('robots.urls')),
    (r'^i18n/', include('django.conf.urls.i18n')),

    (r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict),

    (r'^jsi18n/(?P<packages>\S+?)/$', 'django.views.i18n.javascript_catalog'),

    # Uncomment the next line to enable the admin:
     url(r'^admin/', include(admin.site.urls)),

     url( r'^', include( 'userapp.urls' ) ),

     url( r'^institute/', include( 'InstituteInfo.urls' ) ),
	
     url( r'^group_config/', include( 'group_config.urls' ) ),

     url( r'^student/', include( 'studentinfo.urls' ) ),

     url( r'^faculty/', include( 'facultyinfo.urls' ) ),

    # url( r'^(?P<user_id>[-\d]+)/(?P<username>[-\w]+)/$', FacultyDetail.as_view(), name = 'faculty_detail' ),

     #url( r'^online-exam/', include( 'questionnaire.urls' ) ),

     url( r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT} ),

     url( r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT} ),

     #(r'^photologue/', include('photologue.urls')),

     # (r'^messages/', include('persistent_messages.urls')),

     # (r'^comments/', include('django.contrib.comments.urls')),
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^rosetta/', include('rosetta.urls')),
    )
urlpatterns += staticfiles_urlpatterns()

userapp/urls.py
__author__ = 'harshit'

from django.conf.urls.defaults import patterns , url
from django.contrib.auth.views import *
from userapp.views import *
from userapp.profile import ProfileSubmission
from userapp.forms import Password_Reset_Form


urlpatterns = patterns( '',

         url( r'^$', EndUserLogin.as_view(), name = 'login' ),

         url( r'^signup$', EndUserRegistration.as_view(), name = 'register' ),

         url( r'^profile_submission/$', ProfileSubmission.as_view(), name = 'profile_submission' ),

         url( r'^forgetpassword/$', 'django.contrib.auth.views.password_reset', {'password_reset_form':Password_Reset_Form}, name = 'forgetpassword' ),

         url( r'^password_reset_done/$', 'django.contrib.auth.views.password_reset_done'),

         url( r'^reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm', {'template_name' : 'registration/password_reset.html',  'post_reset_redirect': '/logout/' }),

         url( r'^changepassword/$', ChangePassword.as_view() , name = 'changepassword' ),

         url( r'^logout/$', logout , name = 'logout' ),

    #new url
         url( r'^(?P<user_id>[-\d]+)/profile/(?P<username>[-\w]+)',ProfileSubmission.as_view(), name = 'profile'),

         url( r'^(?P<username>[-\w]+)/mygroups/$',get_group_listing, name = 'group_listing'),

         url( r'^(?P<username>[-\w]+)/$', UserProfile.as_view(), name = 'institute_profile' ),

         url( r'^(?P<username>[-\w]+)/connect/$', connect_user, name = 'connect' ),

         url( r'^(?P<username>[-\w]+)/pending_requests/$', PendingStudentListView.as_view(), name = 'pending_request' ),

         # url( r'^(?P<username>[-\w]+)/pending_requests/$', PendingStudentListView.as_view(), name = 'pending_request' ),

         url( r'^(?P<username>[-\w]+)/bulletins_by_faculty/$', fetch_faculty_bulletins, name = 'bulletins_by_faculty' ),

         url( r'^(?P<username>[-\w]+)/students/$', students_connected_to_user , name = 'connected_students' ),

         url( r'^(?P<username>[-\w]+)/faculty/$', faculty_connected_to_user, name = 'connected_faculty' ),

         url( r'^find/user/$', UserListView.as_view(), name = 'search_user' ),

         url( r'^delete/(?P<pk>[-\d]+)/$', MyDeleteView.as_view(), name = 'delete_post' ),
)

master/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from InstituteInfo.choices import INSTITUTE_TYPE,LIST_YEAR,USER_TYPE
from studentinfo.choices import STATUS_CHOICES
from django.db import models
from django.contrib.auth.models import ( AbstractUser)
# from group_config.models import UserGroup


def imagepath(instance, filename):
    """ Computes the infrastructure images upload path """
    return "uploads/user_images/%s/%s" % (instance.user.id, str(filename).replace(" ", "-"))


class MyUser(AbstractUser):
    photo = models.ImageField(upload_to=imagepath)
    user_type = models.CharField(max_length=25, choices=USER_TYPE)
    institute_type = models.CharField(max_length=25, choices=INSTITUTE_TYPE )
    establishment_year = models.IntegerField(blank=True, null=True, choices=LIST_YEAR )
    address = models.TextField()
    profile = models.BooleanField(default=False, blank=True)
    status = models.CharField(max_length=100, choices=STATUS_CHOICES, default='Pending')
    qualification = models.CharField(max_length=100)
    work_experience = models.CharField(max_length=100)
    rating = models.FloatField(default=0)
    unique_number = models.CharField(max_length=30)
    connections = models.ManyToManyField("self", through='UserSelf', symmetrical=False)

    def __unicode__(self):
        return self.username

def post_save_default_image(sender, instance, **kwargs):
    if kwargs['created'] is True:
        photo = "uploads/user_images/%s/%s" % ('default', str('images.jpeg').replace(" ", "-"))
        instance.photo = photo
        instance.save()

class UserSelf(models.Model):
    source = models.ForeignKey(MyUser, related_name='source')
    target = models.ForeignKey(MyUser, related_name='target')
    group = models.ForeignKey('group_config.UserGroup', null=True, blank=True)

post_save.connect(post_save_default_image, sender= MyUser)

userapp/models.py
from django.db import models
from django.contrib.auth.models import User, Group

# Create your models here.

REGISTRATION_CHOICES = (
    ('Institute','Institute'),
    ('Student','Student')
    )

class LoginDetail( models.Model ):

    # user = models.ForeignKey( User, related_name = 'user_detail' )
    name = models.CharField( max_length = 500 )
    last_login = models.DateTimeField()
    ip_address = models.CharField( max_length = 150, blank = True, null = True )


class Group(Group):
    pass

userapp/views.py
# Create your views here.
from django.contrib.auth.forms import AuthenticationForm
from django.template.context import RequestContext
from userapp.forms import  LoginAuthenticationForm, RegistrationForm
from django.views.generic.base import  View, TemplateView
from django.contrib.auth import authenticate, login as auth_login
from django.contrib.auth.models import User, Group
from django.http import  HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response
from studentinfo.forms import StudentInfoForm
from InstituteInfo.forms import InstituteInfoForm
from django.core.urlresolvers import reverse
from studentinfo.models import StudentInfo
from InstituteInfo.models import *
from InstituteInfo.views import extract_logo_path
from django.views.generic.base import RedirectView
from django.contrib.auth.forms import SetPasswordForm
from facultyinfo.models import FacultyInfo




class EndUserRegistration( TemplateView ):
    template_name = 'userapp/signup.html'


    def post( self, request, *args, **kwargs ):

        registration_form = RegistrationForm( data = self.request.POST )

        if  registration_form.is_valid():
            registration_form.save()
            user = User.objects.get(username = request.POST['username'])
            user.first_name = request.POST['first_name']
            user.first_name = request.POST['first_name']
            user.save()

            group = Group.objects.get(name = self.request.POST['groups'])
            group.user_set.add(user)
            form = AuthenticationForm( data = request.POST )

            auth_login( request, authenticate( username = request.POST['username'], password = request.POST['password1'] ) )
#            return HttpResponseRedirect(reverse('profile_submission'))
            return HttpResponseRedirect(reverse('profile', args = (self.request.user.id,self.request.user.username)))
        else:
            return render_to_response( 'userapp/signup.html', locals(), context_instance = RequestContext( self.request ) )


class EndUserLogin( TemplateView ):
    template_name = 'userapp/index.html'


    def get(self,request,**kwargs):
        if self.request.user.is_authenticated():
            if 'Institute' in self.request.user.groups.values_list('name',flat = True):
                try:
                    InstitueInfo.objects.get(user = request.user).profile
                    return HttpResponseRedirect(reverse('institute_profile'))
                except:
                    return HttpResponseRedirect(reverse('profile', args = (self.request.user.id,self.request.user.username)))
            elif 'Student' in self.request.user.groups.values_list('name',flat = True) :
                try:
                    StudentInfo.objects.get(user = request.user).profile
                    return HttpResponseRedirect(reverse('student_inbox'))
                except:
                    return HttpResponseRedirect(reverse('profile', args = (self.request.user.id,self.request.user.username)))

            elif 'Faculty' in self.request.user.groups.values_list('name',flat = True) :
               try:
                   FacultyInfo.objects.get(user = request.user).profile
                   return HttpResponseRedirect(reverse('faculty_detail', args = (self.request.user.id,self.request.user.username)))
               except:
                return HttpResponseRedirect(reverse('profile', args = (self.request.user.id,self.request.user.username)))

        else:
            login_form = LoginAuthenticationForm()
            registration_form = RegistrationForm()
            return render_to_response( 'userapp/index.html', locals(), context_instance = RequestContext( self.request ) )

    def post(self,request,*args,**kwargs):
        self.request = request
        login_form = LoginAuthenticationForm(data= self.request.POST)
        registration_form = RegistrationForm()
        if  login_form.is_valid():
            self.redirect_to = self.request.POST.get('next','/')
            auth_login( self.request, login_form.get_user() )

            if self.request.session.test_cookie_worked():
                self.request.session.delete_test_cookie()

            self.user = User.objects.get( username = self.request.POST['username'] )

            if 'Institute' in self.request.user.groups.values_list('name',flat = True):
                try:
                    InstitueInfo.objects.get(user = request.user).profile
                    return HttpResponseRedirect(reverse('institute_profile'))
                except:
                    return HttpResponseRedirect(reverse('profile', args = (self.request.user.id,self.request.user.username)))
            elif 'Student' in self.request.user.groups.values_list('name',flat = True) :
                try:
                    StudentInfo.objects.get(user = request.user).profile
                    return HttpResponseRedirect(reverse('student_inbox'))
                except:
                    return HttpResponseRedirect(reverse('profile', args = (self.request.user.id,self.request.user.username)))

            elif 'Faculty' in self.request.user.groups.values_list('name',flat = True) :
#                try:
#                    return  HttpResponse('Tetsing Process ..')
#                    StudentInfo.objects.get(user = request.user).profile
#                    return HttpResponseRedirect(reverse('student_inbox'))
#                except:
                return HttpResponseRedirect(reverse('profile', args = (self.request.user.id,self.request.user.username)))
#

        else:
            err_msg = 'Enter a Valid Username password'
            return render_to_response('userapp/index.html',locals(),context_instance = RequestContext(self.request))



class ChangePassword( TemplateView ):
     template_name = 'userapp/change_password.html'

     def get_context_data( self, *kwargs):
         change_password_form = SetPasswordForm(self.request.user)
         return locals()

     def post(self, request, *args , **kwargs):
         change_password_form = SetPasswordForm(self.request.user, self.request.POST )
         if change_password_form.is_valid():
             change_password_form.save()

         return HttpResponse('Password Changed Successfully')


def logout( request ):
    from django.contrib.auth import logout
    logout( request )
    response = HttpResponseRedirect( '/' )
    return response

templates/userapp/change_password.html
{% extends "layouts/layout_base_2_columns.html" %}



{% block A_1 %}

    <form class ="form-changepassword" method="post">{% csrf_token %}
        <h2 class="form-horizontal-heading">Change Password</h2>
        {% for each_field in change_password_form.visible_fields %}
        <div class="control-group">
            <div class="controls">
                {%  if each_field.errors %}
                {{ each_field.errors }}
                {% endif %}
                {{each_field}}
            </div>
        </div>
        {% endfor %}
        <input class="btn btn-primary" type="submit" value ="Change Password"></button>
    </form>


{% endblock A_1 %}

templates/userapp/index.html
{% extends "layouts/layout_base_2_columns.html" %}

{% block A_1 %}
<div class="container-fluid" style="">
<div class="row-fluid">
<div class="homePageContainer span8">
    <img src="http://www.w3resource.com/responsive-web-design/template1/8399337241_52f0280326_b.jpg" style=""/>
</div>
<div class="span4">
<div class ="login row-fluid">
    <form class="login-class span12" action="/" method="post">{% csrf_token %}
        <h2 class="form-horizontal-heading span12">Please Login</h2>
        <div class="control-group span12 row-fluid" style="padding: 0px 30px 0px 30px;">
            <div class="controls row-fluid">

                {% if err_msg %}
                {{ err_msg }}
                {% endif %}
                {% for each_field in login_form.visible_fields %}
                {% if each_field.errors %}
                {{ each_field.errors }}
                {% endif %}
                {{ each_field}}<br><br>
                {% endfor %}
                <label class="checkbox">
                    <input type="checkbox"> Remember me
                </label>
            </div>
        </div>
        <input class="btn btn-primary" type="submit" value ="Login"></button>
    </form>
</div>
<div class="form-signin2 span12">
    <div class ="registerInside">
        <a href="#mySignupModal" role="button" class="btn btn-primary" data-toggle="modal">Registered User.SignUp Here</a>
    </div>
</div>
</div>
</div>
</div>
<!--</div>-->

<div id="mySignupModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="width: 275px; margin-left:-154px">

    <form action="{% url 'register' %}" method="post">{% csrf_token %}
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h2 id="mySignupModalLabel">Please Signup</h2>
        </div>

        <div class="modal-body">
            {% for each_field in registration_form.visible_fields %}
            <div class="control-group">
                <div class="controls">
                    {%  if each_field.errors %}
                    {{ each_field.errors }}
                    {% endif %}
                        <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu">
                            <li><a tabindex="-1" href="#">Action</a></li>
                            <li><a tabindex="-1" href="#">Another action</a></li>
                        </ul>
                        {{each_field}}
                </div>
            </div>
            {% endfor %}
        </div>

        <div class="modal-footer">
            <input class="btn btn-primary" type="submit" value ="Signup"></button>
        </div>
    </form>
</div>

{% endblock A_1 %}

templates/userapp/profile_submission.html
{% extends "layouts/layout_base_2_columns.html" %}
{% block A_1 %}



    <div class ="logo">
        <img  src ="{{ MEDIA_URL }}{{ image_path.0.photo }}" style="width: 100%;height: 100%">
    </div>
    <a href='{% url 'faculty_detail' profile_user.id profile_user.username %}'>Blogs</a>

        <form class="form-profileSub" enctype="multipart/form-data" method="post"> {% csrf_token %}
            <h2><strong>Profile Information</strong></h2>
            {% for each_field in form.visible_fields %}
                <div class="control-group">
                    <label class="control-label" for="id_{{ each_field.label|lower }}">{{ each_field.label }}</label>
                    <div class="controls">
                    {%  if each_field.errors %}
                    {{ each_field.errors }}
                    {% endif %}
                        {% if each_field.name == 'address' %}
                            <textarea id="id_address" name="address" cols="27" rows="4">{{ each_field.value }}</textarea>
                        {% else %}
                            {{ each_field }}
                        {% endif %}

                     </div>
                </div>
            {% endfor %}
            {% if group_type == user_group.0 %}
             <input class="btn btn-primary" type="submit" value ="Submit Profile"></button>
            {% endif %}
        </form>
{% endblock A_1 %}

templates/userapp/signup.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

    {% block css %}
    <link rel="stylesheet" href="{{ MEDIA_URL }}bootstrap/css/bootstrap.css" type="text/css" media="all" />
    {% endblock css %}


    <title>iMagic</title>
    <style>

        body {
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #f5f5f5;
        }
        .form-signin {
            max-width: 300px;
            padding: 19px 29px 29px;
            margin: 0 auto 20px;
            background-color: #fff;
            border: 1px solid #e5e5e5;
            -webkit-border-radius: 5px;
            -moz-border-radius: 5px;
            border-radius: 5px;
            -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
            -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
            box-shadow: 0 1px 2px rgba(0,0,0,.05);
        }
        .form-signin .form-signin-heading,
        .form-signin .checkbox {
            margin-bottom: 10px;
        }
        .form-signin input[type="text"],
        .form-signin input[type="password"] {
            font-size: 16px;
            height: auto;
            margin-bottom: 15px;
            padding: 7px 9px;
        }
    </style>
<body>




 <div class ="container">
    <form class ="form-signin" action="{% url 'register' %}" method="post">{% csrf_token %}
        <h2 class="form-horizontal-heading">Please SignUp</h2>
        {% for each_field in registration_form.visible_fields %}

        <div class="control-group">
            <div class="controls">
                {%  if each_field.errors %}
                {{ each_field.errors }}
                {% endif %}
                {{each_field}}
            </div>
        </div>
        {% endfor %}
        <input class="btn btn-primary" type="submit" value ="Signup"></button>
    </form>
</div>

</body>
<!--<form  method="post" action="{% url 'register' %}"> {% csrf_token %}-->

    <!--{% for each_field in registration_form.visible_fields %}-->

    <!--<label class="left">{{each_field.label}}</label>-->

    <!--{%  if each_field.errors %}-->
        <!--{{ each_field.errors }}-->
    <!--{% endif %}-->
    <!--{{each_field}}-->
    <!--<br>-->
    <!--{% endfor %}-->
    <!--<br>-->

 <!--<input id="id_submit" type="submit"  value="Submit" />-->